### ISSUE TITLE
小程序编辑器提示引入不到模块

### ISSUE THREAD

**Issue by peng** [Chaunjie/rich-text-parser#2]

**Comment by Chaunjie** [comment]
你是怎么引入的呢？

**Comment by peng** [comment]
在pages 文件夹 下面的页面对应的js 文件中，按文档上说明 import parser from 'rich-text-parser'  这样引入的

**Comment by Chaunjie** [comment]
贴个代码出来------------------ 原始邮件 ------------------
发件人: "Zhang Zhipeng"<notifications@github.com>
发送时间: 2019年8月29日(星期四) 晚上8:13
收件人: "Chaunjie/rich-text-parser"<rich-text-parser@noreply.github.com>;
抄送: "禾呈"<894576801@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [Chaunjie/rich-text-parser] 小程序编辑器提示引入不到模块 (#2)



在pages 文&#x4EF6;夹 下面的页面对应的js 文&#x4EF6;中，按文档上说明 import parser from 'rich-text-parser'  这样引入的
 
&mdash;

**Comment by peng** [comment]
![Screen Shot 2019-08-30 at 9 47 33 AM](https://user-images.githubusercontent.com/26745086/63987577-54d78500-cb0b-11e9-85a2-6bf79b66f487.png)
![Screen Shot 2019-08-30 at 9 47 47 AM](https://user-images.githubusercontent.com/26745086/63987587-5ef98380-cb0b-11e9-858a-ce2025c3385f.png)
<img width="767" alt="Screen Shot 2019-08-30 at 9 48 01 AM" src="https://user-images.githubusercontent.com/26745086/63987597-6b7ddc00-cb0b-11e9-8eb2-e3b18b7a9cda.png">
微信开发者工具版本 1.02.1907300

**Comment by Chaunjie** [comment]
@peng 你使用require试试

**Comment by peng** [comment]
require 也是报同样的错误

**Comment by Chaunjie** [comment]
不科学吧，那你直接把我这个包拷贝到你的项目然后正常引入试试

**Comment by peng** [comment]
@Chaunjie  嗯嗯后来我拷贝过去的，小程序就是各种离奇的问题
